name: 'Hello World'
description: 'Greet someone, record the time, and test build number'
inputs:
  prefix:
    description: 'Prefix for build-number<num> tag'
    required: false
    default: 'build-number-'
  token:
    description: 'GitHub token to create and deltet refs'
    required: false # only needed for very first job
outputs:
  build_number:
    description: 'Build tag number'
runs:
  using: 'node16'
  main: 'index.js'
