name: 'Hello World'
description: 'Greet someone, record the time, and test build number'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
  prefix:
    description: 'Prefix for build-number<num> tag'
    required: false
outputs:
  time:
    description: 'The time we greeted you'
  build_number:
    description: 'Build tag number'
runs:
  using: 'node16'
  main: 'index.js'
